export const sampleData = `<p>Normal Text With normal font Size</p><p><br></p><h1>Heading 1</h1><p><br></p><h2><span style="color: rgb(17, 24, 28);">Heading 2</span></h2><p><br></p><h3><span style="color: rgb(17, 24, 28);">Heading 3</span></h3><p><br></p><h4><span style="color: rgb(17, 24, 28);">Heading 4</span></h4><p><br></p><h5><span style="color: rgb(17, 24, 28);">Heading 5</span></h5><p><br></p><h6><span style="color: rgb(17, 24, 28);">Heading 6</span></h6><p><br></p><p><br></p><p>This is SuperScript (a+b)<sup>2</sup></p><p><br></p><p>This is subScript ( h<sub style="color: rgb(17, 24, 28);">2</sub><span style="color: rgb(17, 24, 28);">0 ) ( h</span><sub style="color: rgb(17, 24, 28);">2</sub><span style="color: rgb(17, 24, 28);">s0</span><sub style="color: rgb(17, 24, 28);">4</sub><span style="color: rgb(17, 24, 28);">)</span></p><p><br></p><p><br></p><p><span class="ql-size-huge" style="color: rgb(17, 24, 28);">Huge Font Size</span></p><p><br></p><p><span class="ql-size-large" style="color: rgb(17, 24, 28);">Large Font Size</span></p><p><br></p><p><span class="ql-size-small">Small Font Size</span></p><p><br></p><p><br></p><p><span style="color: rgb(254, 153, 0);">Text in </span><span style="color: rgb(234, 153, 153);">Different Colors</span>. <span style="color: rgb(204, 65, 37);">You </span><span style="color: rgb(204, 0, 0);">can </span><span style="color: rgb(166, 27, 0);">add</span> <span style="color: rgb(0, 255, 255);">different </span><span style="color: rgb(75, 133, 232);">color </span><span style="color: rgb(164, 194, 244);">to </span><span style="color: rgb(255, 0, 255);">your </span><span style="color: rgb(19, 0, 255);">text</span></p><p><br></p><p><span class="ql-size-small" style="color: rgb(181, 167, 213);">This is Yellow color text with small font size</span></p><p><span class="ql-size-small" style="color: rgb(254, 0, 0);">This is red color text with small font size</span></p><p><span class="ql-size-small" style="color: rgb(19, 0, 255);">This is blue color text with small font size</span></p><p><br></p><p><br></p><p><span style="background-color: rgb(254, 255, 0); color: rgb(0, 0, 0);">This is yellow HighLight with black Text</span></p><p><br></p><p><span style="color: rgb(241, 194, 49); background-color: rgb(59, 120, 216);">This is a purple HighLight Textwith orange text</span></p><p><br></p><p><span class="ql-size-small" style="background-color: rgb(254, 255, 0); color: rgb(0, 0, 0);">This is yellow HighLight with black Text with small font size</span></p><p><br></p><p><strong>This is a Bold Text</strong></p><p><br></p><p><u>This is a Underline Text</u></p><p><br></p><p><em>This is an Italic Text</em></p><p><br></p><p><s>Thsi is a StrickThrough Text</s></p><p><br></p><p><strong><em>This is Italic with Bold</em></strong></p><p><br></p><h1><span class="ql-size-huge">This is a Image</span></h1><p><br></p><p><span class="ql-size-small">﻿</span><p><br></p><p><br></p><p><strong class="ql-size-huge"><em>This is a Youtube Video</em></strong></p><p><br></p><iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube.com/embed/qmBVxGd--uA?showinfo=0"></iframe><p><br></p><p><br></p><p><br></p><p><a href="https://www.youtube.com/watch?v=qmBVxGd--uA&amp;list=RDqmBVxGd--uA&amp;start_radio=1" rel="noopener noreferrer" target="_blank"><strong><u>Link</u></strong></a> of the Video</p><p><br></p><p><br></p><p><strong class="ql-size-huge"><em>You Can Try All Other Option By Your-Self</em></strong></p><p><strong class="ql-size-huge"><em>Thank You!!</em></strong></p>`;

const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "NAME", uid: "name", sortable: true },
  { name: "AGE", uid: "age", sortable: true },
  { name: "ROLE", uid: "role", sortable: true },
  { name: "TEAM", uid: "team" },
  { name: "EMAIL", uid: "email" },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "paused",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "active",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "paused",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "active",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "active",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export { columns, users, statusOptions };
