export enum NotificationType {
  ProductCreated = "ProductCreated",
  ProductUpdated = "ProductUpdated",
  ProductDeleted = "ProductDeleted",
  ProductStockOut = "ProductStock Out",
  CategoryCreated = "CategoryCreated",
  CategoryUpdated = "CategoryUpdated",
  CategoryDeleted = "CategoryDeleted",
  BlogCreated = "BlogCreated",
  BlogUpdated = "BlogUpdated",
  BlogDeleted = "BlogDeleted",
  NewOrderPlaced = "NewOrderPlaced",
  OrderCanceled = "OrderCanceled",
  OrderReturned = "OrderReturned",
  NewProductReview = "NewProductReview",
  NewRegistration = "NewRegistration",
  NewComment = "NewComment",
  Review = "Review",
}
