export interface OrderItem {
  name: string;
  sku: string;
  price: number;
  quantity: number;
  category: string;
}

export interface OrderData {
  orderId: string;
  orderDate: string;
  orderStatus: string;
  orderType: string;
  orderSource: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  userId: string;
  shippingAddress: string;
  totalValue: number;
  paymentMethod: string;
  paymentStatus: string;
  transactionId: string;
  items: OrderItem[];
  shippingMethod: string;
  shippingFee: number;
  courierName: string;
  trackingNumber: string;
  expectedDeliveryDate: string | null;
  deliveryStatus: string;
  invoiceNumber: string;
  orderNotes: string | null;
  adminComments: string | null;
  subtotal: number;
  discount: number;
}

export const orders: OrderData[] = [
  {
    orderId: "#ORD12345",
    orderDate: "2023-03-15T10:30:00",
    orderStatus: "Delivered",
    orderType: "Normal",
    orderSource: "Website",
    customerName: "John Smith",
    customerEmail: "john.smith@example.com",
    customerPhone: "+1 (555) 123-4567",
    userId: "USR7890",
    shippingAddress: "123 Main St, Apt 4B, New York, NY 10001",
    totalValue: 149.97,
    paymentMethod: "Credit Card",
    paymentStatus: "Paid",
    transactionId: "TXN987654321",
    items: [
      {
        name: "Wireless Headphones",
        sku: "SKU-WH100",
        price: 79.99,
        quantity: 1,
        category: "Electronics",
      },
      {
        name: "Phone Case",
        sku: "SKU-PC200",
        price: 24.99,
        quantity: 2,
        category: "Accessories",
      },
      {
        name: "Screen Protector",
        sku: "SKU-SP300",
        price: 19.99,
        quantity: 1,
        category: "Accessories",
      },
    ],
    shippingMethod: "Express",
    shippingFee: 12.99,
    courierName: "FedEx",
    trackingNumber: "FDX123456789",
    expectedDeliveryDate: "2023-03-18T00:00:00",
    deliveryStatus: "Delivered",
    invoiceNumber: "INV-2023-12345",
    orderNotes: "Please leave package at the door",
    adminComments: "VIP customer, ensure timely delivery",
    subtotal: 149.97,
    discount: 0,
  },
  {
    orderId: "#ORD12346",
    orderDate: "2023-03-16T14:45:00",
    orderStatus: "Processing",
    orderType: "Normal",
    orderSource: "Mobile App",
    customerName: "Jane Doe",
    customerEmail: "jane.doe@example.com",
    customerPhone: "+1 (555) 987-6543",
    userId: "USR7891",
    shippingAddress: "456 Oak Ave, Seattle, WA 98101",
    totalValue: 349.98,
    paymentMethod: "PayPal",
    paymentStatus: "Paid",
    transactionId: "TXN987654322",
    items: [
      {
        name: "Smart Watch",
        sku: "SKU-SW100",
        price: 249.99,
        quantity: 1,
        category: "Electronics",
      },
      {
        name: "Watch Band",
        sku: "SKU-WB200",
        price: 49.99,
        quantity: 2,
        category: "Accessories",
      },
    ],
    shippingMethod: "Standard",
    shippingFee: 8.99,
    courierName: "UPS",
    trackingNumber: "UPS987654321",
    expectedDeliveryDate: "2023-03-22T00:00:00",
    deliveryStatus: "Shipped",
    invoiceNumber: "INV-2023-12346",
    orderNotes: null,
    adminComments: null,
    subtotal: 349.98,
    discount: 0,
  },
  {
    orderId: "#ORD12347",
    orderDate: "2023-03-17T09:15:00",
    orderStatus: "Shipped",
    orderType: "Pre-order",
    orderSource: "Website",
    customerName: "Robert Johnson",
    customerEmail: "robert.johnson@example.com",
    customerPhone: "+1 (555) 456-7890",
    userId: "USR7892",
    shippingAddress: "789 Pine St, San Francisco, CA 94101",
    totalValue: 899.99,
    paymentMethod: "Credit Card",
    paymentStatus: "Paid",
    transactionId: "TXN987654323",
    items: [
      {
        name: "Laptop",
        sku: "SKU-LP100",
        price: 899.99,
        quantity: 1,
        category: "Electronics",
      },
    ],
    shippingMethod: "Express",
    shippingFee: 14.99,
    courierName: "DHL",
    trackingNumber: "DHL123456789",
    expectedDeliveryDate: "2023-03-20T00:00:00",
    deliveryStatus: "Out for Delivery",
    invoiceNumber: "INV-2023-12347",
    orderNotes: "Call before delivery",
    adminComments: null,
    subtotal: 899.99,
    discount: 0,
  },
  {
    orderId: "#ORD12348",
    orderDate: "2023-03-18T16:30:00",
    orderStatus: "Pending",
    orderType: "Normal",
    orderSource: "Marketplace",
    customerName: "Emily Wilson",
    customerEmail: "emily.wilson@example.com",
    customerPhone: "+1 (555) 789-0123",
    userId: "USR7893",
    shippingAddress: "321 Maple Rd, Chicago, IL 60601",
    totalValue: 74.98,
    paymentMethod: "Bank Transfer",
    paymentStatus: "Unpaid",
    transactionId: "TXN987654324",
    items: [
      {
        name: "T-Shirt",
        sku: "SKU-TS100",
        price: 24.99,
        quantity: 2,
        category: "Clothing",
      },
      {
        name: "Jeans",
        sku: "SKU-JN200",
        price: 49.99,
        quantity: 1,
        category: "Clothing",
      },
    ],
    shippingMethod: "Standard",
    shippingFee: 5.99,
    courierName: "USPS",
    trackingNumber: "",
    expectedDeliveryDate: "2023-03-25T00:00:00",
    deliveryStatus: "Not Shipped",
    invoiceNumber: "INV-2023-12348",
    orderNotes: null,
    adminComments: "Awaiting payment confirmation",
    subtotal: 99.97,
    discount: 25.0,
  },
  {
    orderId: "#ORD12349",
    orderDate: "2023-03-19T11:20:00",
    orderStatus: "Canceled",
    orderType: "Normal",
    orderSource: "Website",
    customerName: "Michael Brown",
    customerEmail: "michael.brown@example.com",
    customerPhone: "+1 (555) 234-5678",
    userId: "USR7894",
    shippingAddress: "654 Birch Blvd, Miami, FL 33101",
    totalValue: 129.99,
    paymentMethod: "Credit Card",
    paymentStatus: "Refunded",
    transactionId: "TXN987654325",
    items: [
      {
        name: "Bluetooth Speaker",
        sku: "SKU-BS100",
        price: 129.99,
        quantity: 1,
        category: "Electronics",
      },
    ],
    shippingMethod: "Standard",
    shippingFee: 7.99,
    courierName: "",
    trackingNumber: "",
    expectedDeliveryDate: null,
    deliveryStatus: "Not Shipped",
    invoiceNumber: "INV-2023-12349",
    orderNotes: null,
    adminComments: "Customer requested cancellation",
    subtotal: 129.99,
    discount: 0,
  },
  {
    orderId: "#ORD12350",
    orderDate: "2023-03-20T13:45:00",
    orderStatus: "Processing",
    orderType: "Subscription",
    orderSource: "Mobile App",
    customerName: "Sarah Davis",
    customerEmail: "sarah.davis@example.com",
    customerPhone: "+1 (555) 345-6789",
    userId: "USR7895",
    shippingAddress: "987 Cedar Ln, Austin, TX 78701",
    totalValue: 59.99,
    paymentMethod: "PayPal",
    paymentStatus: "Paid",
    transactionId: "TXN987654326",
    items: [
      {
        name: "Monthly Coffee Subscription",
        sku: "SKU-CS100",
        price: 59.99,
        quantity: 1,
        category: "Food & Beverage",
      },
    ],
    shippingMethod: "Standard",
    shippingFee: 4.99,
    courierName: "USPS",
    trackingNumber: "USPS123456789",
    expectedDeliveryDate: "2023-03-24T00:00:00",
    deliveryStatus: "Not Shipped",
    invoiceNumber: "INV-2023-12350",
    orderNotes: "Leave with neighbor if not home",
    adminComments: null,
    subtotal: 59.99,
    discount: 0,
  },
  {
    orderId: "#ORD12351",
    orderDate: "2023-03-21T10:10:00",
    orderStatus: "Delivered",
    orderType: "Normal",
    orderSource: "Website",
    customerName: "David Miller",
    customerEmail: "david.miller@example.com",
    customerPhone: "+1 (555) 456-7890",
    userId: "USR7896",
    shippingAddress: "753 Elm St, Denver, CO 80201",
    totalValue: 199.98,
    paymentMethod: "Credit Card",
    paymentStatus: "Paid",
    transactionId: "TXN987654327",
    items: [
      {
        name: "Running Shoes",
        sku: "SKU-RS100",
        price: 99.99,
        quantity: 2,
        category: "Footwear",
      },
    ],
    shippingMethod: "Express",
    shippingFee: 9.99,
    courierName: "FedEx",
    trackingNumber: "FDX987654321",
    expectedDeliveryDate: "2023-03-23T00:00:00",
    deliveryStatus: "Delivered",
    invoiceNumber: "INV-2023-12351",
    orderNotes: null,
    adminComments: null,
    subtotal: 199.98,
    discount: 0,
  },
  {
    orderId: "#ORD12352",
    orderDate: "2023-03-22T15:30:00",
    orderStatus: "Refunded",
    orderType: "Normal",
    orderSource: "Marketplace",
    customerName: "Jennifer Taylor",
    customerEmail: "jennifer.taylor@example.com",
    customerPhone: "+1 (555) 567-8901",
    userId: "USR7897",
    shippingAddress: "159 Oak Dr, Boston, MA 02101",
    totalValue: 45.99,
    paymentMethod: "PayPal",
    paymentStatus: "Refunded",
    transactionId: "TXN987654328",
    items: [
      {
        name: "Desk Lamp",
        sku: "SKU-DL100",
        price: 45.99,
        quantity: 1,
        category: "Home Decor",
      },
    ],
    shippingMethod: "Standard",
    shippingFee: 6.99,
    courierName: "UPS",
    trackingNumber: "UPS123456789",
    expectedDeliveryDate: "2023-03-26T00:00:00",
    deliveryStatus: "Returned",
    invoiceNumber: "INV-2023-12352",
    orderNotes: null,
    adminComments: "Item arrived damaged, full refund issued",
    subtotal: 45.99,
    discount: 0,
  },
  {
    orderId: "#ORD12353",
    orderDate: "2023-03-23T09:45:00",
    orderStatus: "Processing",
    orderType: "COD",
    orderSource: "Website",
    customerName: "Thomas Anderson",
    customerEmail: "thomas.anderson@example.com",
    customerPhone: "+1 (555) 678-9012",
    userId: "USR7898",
    shippingAddress: "357 Pine Ave, Portland, OR 97201",
    totalValue: 299.97,
    paymentMethod: "Cash on Delivery",
    paymentStatus: "Unpaid",
    transactionId: "",
    items: [
      {
        name: "Coffee Maker",
        sku: "SKU-CM100",
        price: 199.99,
        quantity: 1,
        category: "Kitchen Appliances",
      },
      {
        name: "Coffee Beans",
        sku: "SKU-CB200",
        price: 24.99,
        quantity: 4,
        category: "Food & Beverage",
      },
    ],
    shippingMethod: "Standard",
    shippingFee: 8.99,
    courierName: "DHL",
    trackingNumber: "",
    expectedDeliveryDate: "2023-03-28T00:00:00",
    deliveryStatus: "Not Shipped",
    invoiceNumber: "INV-2023-12353",
    orderNotes: "Call before delivery",
    adminComments: "Verify ID before accepting payment",
    subtotal: 299.97,
    discount: 0,
  },
  {
    orderId: "#ORD12354",
    orderDate: "2023-03-24T14:20:00",
    orderStatus: "Pending",
    orderType: "Pre-order",
    orderSource: "Mobile App",
    customerName: "Lisa Johnson",
    customerEmail: "lisa.johnson@example.com",
    customerPhone: "+1 (555) 789-0123",
    userId: "USR7899",
    shippingAddress: "852 Maple St, Atlanta, GA 30301",
    totalValue: 1299.99,
    paymentMethod: "Credit Card",
    paymentStatus: "Partially Paid",
    transactionId: "TXN987654330",
    items: [
      {
        name: "Gaming Console",
        sku: "SKU-GC100",
        price: 499.99,
        quantity: 1,
        category: "Electronics",
      },
      {
        name: "4K TV",
        sku: "SKU-TV200",
        price: 799.99,
        quantity: 1,
        category: "Electronics",
      },
    ],
    shippingMethod: "Express",
    shippingFee: 19.99,
    courierName: "",
    trackingNumber: "",
    expectedDeliveryDate: "2023-04-05T00:00:00",
    deliveryStatus: "Not Shipped",
    invoiceNumber: "INV-2023-12354",
    orderNotes: "Handle with care",
    adminComments: "Awaiting remaining payment",
    subtotal: 1299.98,
    discount: 0,
  },
];
