const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "NAME", uid: "name", sortable: true },
  { name: "PRICE", uid: "price", sortable: true },
  { name: "CATEGORY", uid: "category", sortable: true },
  { name: "SUB_CATEGORY", uid: "subcategory" },
  { name: "CREATED AT", uid: "Created_At" },
  { name: "STOCK", uid: "stock" },
  { name: "SIZE", uid: "size" },
  { name: "COLOR", uid: "color" },
  // { name: "EDITOR", uid: "email" },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  // { name: "In_Stock", uid: "In_Stock" },
  { name: "Stock_Out", uid: "Stock_Out" },
  // { name: "Draft", uid: "Draft" },
];

const users = [
  {
    id: 1,
    name: "Hunfredo",
    price: 371.82,
    status: "Stock_Out",
    stock: 847,
    description:
      "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam",
    image: "https://picsum.photos/seed/product1/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Orange",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 2,
    name: "Anny",
    price: 510.41,
    status: "Stock_Out",
    stock: 924,
    description:
      "ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed",
    image: "https://picsum.photos/seed/product2/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Aquamarine",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 3,
    name: "Blondie",
    price: 486.35,
    status: "Stock_Out",
    stock: 115,
    description:
      "ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis",
    image: "https://picsum.photos/seed/product3/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Blue",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 4,
    name: "Gale",
    price: 99.58,
    status: "Draft",
    stock: 667,
    description:
      "ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget",
    image: "https://picsum.photos/seed/product4/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Fuscia",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 5,
    name: "Klemens",
    price: 356.69,
    status: "In_Stock",
    stock: 146,
    description:
      "eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer",
    image: "https://picsum.photos/seed/product5/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Goldenrod",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 6,
    name: "Mathe",
    price: 437.06,
    status: "In_Stock",
    stock: 360,
    description:
      "semper rutrum nulla nunc purus phasellus in felis donec semper sapien a",
    image: "https://picsum.photos/seed/product6/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Turquoise",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 7,
    name: "Mariann",
    price: 638.66,
    status: "Draft",
    stock: 794,
    description:
      "hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut",
    image: "https://picsum.photos/seed/product7/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Khaki",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 8,
    name: "Ranee",
    price: 897.77,
    status: "Draft",
    stock: 436,
    description:
      "lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat",
    image: "https://picsum.photos/seed/product8/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Mauv",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 9,
    name: "Marillin",
    price: 88.48,
    status: "Stock_Out",
    stock: 901,
    description:
      "pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est",
    image: "https://picsum.photos/seed/product9/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Puce",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 10,
    name: "Shawnee",
    price: 622.46,
    status: "Draft",
    stock: 303,
    description:
      "egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis",
    image: "https://picsum.photos/seed/product10/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Turquoise",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 11,
    name: "Marabel",
    price: 607.54,
    status: "Stock_Out",
    stock: 635,
    description:
      "in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam",
    image: "https://picsum.photos/seed/product11/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Violet",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 12,
    name: "Fae",
    price: 873.66,
    status: "Draft",
    stock: 760,
    description:
      "nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit",
    image: "https://picsum.photos/seed/product12/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Crimson",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 13,
    name: "Lisa",
    price: 613.75,
    status: "Draft",
    stock: 490,
    description:
      "sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam",
    image: "https://picsum.photos/seed/product13/300/300.webp",
    category: "clothing",
    subcategory: "dresses",
    color: "Puce",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 14,
    name: "Pepillo",
    price: 413.21,
    status: "In_Stock",
    stock: 107,
    description:
      "duis bibendum morbi non quam nec dui luctus rutrum nulla tellus",
    image: "https://picsum.photos/seed/product14/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Goldenrod",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 15,
    name: "Patrice",
    price: 814.91,
    status: "Stock_Out",
    stock: 210,
    description:
      "sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer",
    image: "https://picsum.photos/seed/product15/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Orange",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 16,
    name: "Reidar",
    price: 970.85,
    status: "Stock_Out",
    stock: 765,
    description:
      "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at",
    image: "https://picsum.photos/seed/product16/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Maroon",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 17,
    name: "Caryl",
    price: 76.36,
    status: "Stock_Out",
    stock: 674,
    description:
      "id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla",
    image: "https://picsum.photos/seed/product17/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Mauv",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 18,
    name: "Maggie",
    price: 390.32,
    status: "In_Stock",
    stock: 725,
    description:
      "magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum",
    image: "https://picsum.photos/seed/product18/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Turquoise",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 19,
    name: "Salmon",
    price: 544.06,
    status: "In_Stock",
    stock: 65,
    description:
      "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
    image: "https://picsum.photos/seed/product19/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Teal",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 20,
    name: "Cory",
    price: 145.59,
    status: "Stock_Out",
    stock: 763,
    description:
      "id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in",
    image: "https://picsum.photos/seed/product20/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Crimson",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 21,
    name: "Karrah",
    price: 197.8,
    status: "Draft",
    stock: 135,
    description:
      "vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    image: "https://picsum.photos/seed/product21/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Violet",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 22,
    name: "Jaynell",
    price: 922.8,
    status: "In_Stock",
    stock: 329,
    description:
      "turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at",
    image: "https://picsum.photos/seed/product22/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Turquoise",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 23,
    name: "Neils",
    price: 33.49,
    status: "Draft",
    stock: 560,
    description:
      "consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",
    image: "https://picsum.photos/seed/product23/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Green",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 24,
    name: "Jasmine",
    price: 680.26,
    status: "In_Stock",
    stock: 116,
    description:
      "tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc",
    image: "https://picsum.photos/seed/product24/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Red",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 25,
    name: "Serena",
    price: 594.17,
    status: "Stock_Out",
    stock: 303,
    description:
      "donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus",
    image: "https://picsum.photos/seed/product25/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Blue",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 26,
    name: "L;urette",
    price: 380.94,
    status: "Draft",
    stock: 135,
    description:
      "lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero",
    image: "https://picsum.photos/seed/product26/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Purple",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 27,
    name: "Mela",
    price: 841.2,
    status: "Draft",
    stock: 317,
    description:
      "convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum",
    image: "https://picsum.photos/seed/product27/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Green",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 28,
    name: "Carny",
    price: 611.4,
    status: "In_Stock",
    stock: 703,
    description:
      "fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar",
    image: "https://picsum.photos/seed/product28/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Purple",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 29,
    name: "Pandora",
    price: 512.01,
    status: "Draft",
    stock: 904,
    description:
      "nunc donec quis orci eget orci vehicula condimentum curabitur in",
    image: "https://picsum.photos/seed/product29/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Purple",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 30,
    name: "Shelbi",
    price: 519.42,
    status: "Draft",
    stock: 593,
    description:
      "sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",
    image: "https://picsum.photos/seed/product30/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Pink",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 31,
    name: "Lyle",
    price: 650.0,
    status: "Draft",
    stock: 568,
    description:
      "pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam",
    image: "https://picsum.photos/seed/product31/300/300.webp",
    category: "clothing",
    subcategory: "dresses",
    color: "Crimson",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 32,
    name: "Alysa",
    price: 328.48,
    status: "Stock_Out",
    stock: 730,
    description: "lorem quisque ut erat curabitur gravida nisi at nibh in hac",
    image: "https://picsum.photos/seed/product32/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Teal",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 33,
    name: "Anet",
    price: 218.34,
    status: "Stock_Out",
    stock: 337,
    description:
      "quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh",
    image: "https://picsum.photos/seed/product33/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Fuscia",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 34,
    name: "Pieter",
    price: 922.09,
    status: "Draft",
    stock: 583,
    description:
      "lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur",
    image: "https://picsum.photos/seed/product34/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Crimson",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 35,
    name: "Conway",
    price: 911.04,
    status: "Draft",
    stock: 994,
    description:
      "aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut",
    image: "https://picsum.photos/seed/product35/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Green",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 36,
    name: "Devan",
    price: 727.87,
    status: "Draft",
    stock: 497,
    description:
      "in est risus auctor sed tristique in tempus sit amet sem fusce",
    image: "https://picsum.photos/seed/product36/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Maroon",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 37,
    name: "Haroun",
    price: 274.11,
    status: "Draft",
    stock: 753,
    description:
      "quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse",
    image: "https://picsum.photos/seed/product37/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Violet",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 38,
    name: "Brigitte",
    price: 847.89,
    status: "In_Stock",
    stock: 478,
    description:
      "vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam",
    image: "https://picsum.photos/seed/product38/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Red",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 39,
    name: "Haleigh",
    price: 660.07,
    status: "Draft",
    stock: 652,
    description:
      "ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum",
    image: "https://picsum.photos/seed/product39/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Khaki",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 40,
    name: "Brant",
    price: 569.21,
    status: "In_Stock",
    stock: 152,
    description:
      "nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue",
    image: "https://picsum.photos/seed/product40/300/300.webp",
    subcategory: "laptops",
    color: "Yellow",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 41,
    name: "Chickie",
    price: 789.23,
    status: "In_Stock",
    stock: 822,
    description:
      "mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus",
    image: "https://picsum.photos/seed/product41/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Maroon",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 42,
    name: "Drew",
    price: 514.31,
    status: "In_Stock",
    stock: 398,
    description:
      "vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum",
    image: "https://picsum.photos/seed/product42/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Mauv",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 43,
    name: "Alaric",
    price: 145.7,
    status: "Draft",
    stock: 446,
    description:
      "platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien",
    image: "https://picsum.photos/seed/product43/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Puce",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 44,
    name: "Blisse",
    price: 816.44,
    status: "Draft",
    stock: 547,
    description:
      "ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus",
    image: "https://picsum.photos/seed/product44/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Goldenrod",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 45,
    name: "Edward",
    price: 361.45,
    status: "Draft",
    stock: 935,
    description:
      "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu",
    image: "https://picsum.photos/seed/product45/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Orange",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 46,
    name: "Bryce",
    price: 492.79,
    status: "Stock_Out",
    stock: 277,
    description:
      "eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa",
    image: "https://picsum.photos/seed/product46/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Khaki",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 47,
    name: "Vanni",
    price: 419.69,
    status: "Draft",
    stock: 804,
    description:
      "risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus",
    image: "https://picsum.photos/seed/product47/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Indigo",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 48,
    name: "Creighton",
    price: 694.92,
    status: "Stock_Out",
    stock: 584,
    description:
      "nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis",
    image: "https://picsum.photos/seed/product48/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Orange",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 49,
    name: "Kipp",
    price: 455.53,
    status: "In_Stock",
    stock: 124,
    description:
      "mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc",
    image: "https://picsum.photos/seed/product49/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Purple",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 50,
    name: "Rivi",
    price: 533.24,
    status: "Draft",
    stock: 683,
    description:
      "nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
    image: "https://picsum.photos/seed/product50/300/300.webp",
    category: "clothing",
    subcategory: "dresses",
    color: "Mauv",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 51,
    name: "Philbert",
    price: 795.19,
    status: "In_Stock",
    stock: 505,
    description:
      "in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor",
    image: "https://picsum.photos/seed/product51/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Indigo",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 52,
    name: "Laina",
    price: 122.68,
    status: "In_Stock",
    stock: 382,
    description:
      "etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id",
    image: "https://picsum.photos/seed/product52/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Khaki",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 53,
    name: "Abby",
    price: 787.2,
    status: "In_Stock",
    stock: 182,
    description:
      "pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique",
    image: "https://picsum.photos/seed/product53/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Khaki",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 54,
    name: "Gianina",
    price: 39.61,
    status: "Draft",
    stock: 680,
    description:
      "cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis",
    image: "https://picsum.photos/seed/product54/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Blue",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 55,
    name: "Sharleen",
    price: 186.77,
    status: "In_Stock",
    stock: 636,
    description:
      "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis",
    image: "https://picsum.photos/seed/product55/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Puce",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 56,
    name: "Juieta",
    price: 790.23,
    status: "Stock_Out",
    stock: 411,
    description:
      "at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia",
    image: "https://picsum.photos/seed/product56/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Green",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 57,
    name: "Bette",
    price: 817.47,
    status: "Stock_Out",
    stock: 653,
    description:
      "odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus",
    image: "https://picsum.photos/seed/product57/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Pink",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 58,
    name: "Amandy",
    price: 983.78,
    status: "Draft",
    stock: 930,
    description:
      "ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede",
    image: "https://picsum.photos/seed/product58/300/300.webp",
    category: "clothing",
    subcategory: "dresses",
    color: "Goldenrod",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 59,
    name: "Hugibert",
    price: 757.2,
    status: "In_Stock",
    stock: 717,
    description:
      "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",
    image: "https://picsum.photos/seed/product59/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Maroon",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 60,
    name: "Carlie",
    price: 455.94,
    status: "In_Stock",
    stock: 991,
    description:
      "venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede",
    image: "https://picsum.photos/seed/product60/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Green",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 61,
    name: "Mathew",
    price: 737.1,
    status: "In_Stock",
    stock: 533,
    description:
      "mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede",
    image: "https://picsum.photos/seed/product61/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Green",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 62,
    name: "Chantalle",
    price: 864.58,
    status: "In_Stock",
    stock: 125,
    description:
      "integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula",
    image: "https://picsum.photos/seed/product62/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Goldenrod",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 63,
    name: "Juana",
    price: 298.36,
    status: "Draft",
    stock: 680,
    description:
      "metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc",
    image: "https://picsum.photos/seed/product63/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Orange",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 64,
    name: "Christin",
    price: 113.93,
    status: "Draft",
    stock: 492,
    description:
      "luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien",
    image: "https://picsum.photos/seed/product64/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Green",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 65,
    name: "Whitaker",
    price: 838.61,
    status: "In_Stock",
    stock: 357,
    description:
      "lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui",
    image: "https://picsum.photos/seed/product65/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Fuscia",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 66,
    name: "Seth",
    price: 973.51,
    status: "In_Stock",
    stock: 433,
    description:
      "erat volutpat in congue etiam justo etiam pretium iaculis justo",
    image: "https://picsum.photos/seed/product66/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Maroon",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 67,
    name: "Fraser",
    price: 595.69,
    status: "In_Stock",
    stock: 666,
    description:
      "pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in",
    image: "https://picsum.photos/seed/product67/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Yellow",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 68,
    name: "Liza",
    price: 284.13,
    status: "In_Stock",
    stock: 375,
    description:
      "lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit",
    image: "https://picsum.photos/seed/product68/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Crimson",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 69,
    name: "Arabele",
    price: 82.5,
    status: "Draft",
    stock: 88,
    description:
      "feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet",
    image: "https://picsum.photos/seed/product69/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Goldenrod",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 70,
    name: "Whitney",
    price: 344.21,
    status: "Stock_Out",
    stock: 937,
    description:
      "convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum",
    image: "https://picsum.photos/seed/product70/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Maroon",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 71,
    name: "Morgen",
    price: 8.8,
    status: "Stock_Out",
    stock: 579,
    description:
      "sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum",
    image: "https://picsum.photos/seed/product71/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Purple",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 72,
    name: "Harbert",
    price: 177.03,
    status: "Draft",
    stock: 68,
    description:
      "vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy",
    image: "https://picsum.photos/seed/product72/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Blue",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 73,
    name: "Tadio",
    price: 997.42,
    status: "In_Stock",
    stock: 25,
    description:
      "odio elementum eu interdum eu tincidunt in leo maecenas pulvinar",
    image: "https://picsum.photos/seed/product73/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Teal",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 74,
    name: "Winifred",
    price: 507.82,
    status: "Stock_Out",
    stock: 693,
    description:
      "amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede",
    image: "https://picsum.photos/seed/product74/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Aquamarine",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 75,
    name: "Paloma",
    price: 360.82,
    status: "Stock_Out",
    stock: 571,
    description:
      "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec",
    image: "https://picsum.photos/seed/product75/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Green",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 76,
    name: "Cinnamon",
    price: 77.71,
    status: "Stock_Out",
    stock: 864,
    description: "nulla dapibus dolor vel est donec odio justo sollicitudin ut",
    image: "https://picsum.photos/seed/product76/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Mauv",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 77,
    name: "Dylan",
    price: 669.75,
    status: "In_Stock",
    stock: 174,
    description:
      "enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac",
    image: "https://picsum.photos/seed/product77/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Mauv",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 78,
    name: "Shay",
    price: 520.69,
    status: "Draft",
    stock: 269,
    description:
      "eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in",
    image: "https://picsum.photos/seed/product78/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Fuscia",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 79,
    name: "Shawna",
    price: 602.63,
    status: "Draft",
    stock: 149,
    description:
      "habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque",
    image: "https://picsum.photos/seed/product79/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Crimson",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 80,
    name: "Knox",
    price: 413.06,
    status: "In_Stock",
    stock: 741,
    description:
      "donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam",
    image: "https://picsum.photos/seed/product80/300/300.webp",
    category: "clothing",
    subcategory: "laptops",
    color: "Red",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 81,
    name: "Carlen",
    price: 809.09,
    status: "In_Stock",
    stock: 613,
    description:
      "donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
    image: "https://picsum.photos/seed/product81/300/300.webp",
    subcategory: "pillows",
    color: "Violet",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 82,
    name: "Ruthe",
    price: 46.99,
    status: "Stock_Out",
    stock: 58,
    description:
      "porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea",
    image: "https://picsum.photos/seed/product82/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Pink",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 83,
    name: "Sawyer",
    price: 332.06,
    status: "Draft",
    stock: 120,
    description:
      "tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam",
    image: "https://picsum.photos/seed/product83/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Red",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 84,
    name: "Xenos",
    price: 61.1,
    status: "Draft",
    stock: 673,
    description:
      "habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum",
    image: "https://picsum.photos/seed/product8/4300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Blue",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 85,
    name: "Victoria",
    price: 132.25,
    status: "Stock_Out",
    stock: 578,
    description: "proin eu mi nulla ac enim in tempor turpis nec euismod",
    image: "https://picsum.photos/seed/product85/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Goldenrod",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 86,
    name: "Eward",
    price: 224.89,
    status: "Stock_Out",
    stock: 718,
    description:
      "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam",
    image: "https://picsum.photos/seed/product86/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Crimson",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 87,
    name: "Jemmy",
    price: 71.69,
    status: "Stock_Out",
    stock: 412,
    description:
      "convallis nunc proin at turpis a pede posuere nonummy integer non velit",
    image: "https://picsum.photos/seed/product87/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Fuscia",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 88,
    name: "Karisa",
    price: 536.32,
    status: "Draft",
    stock: 194,
    description:
      "suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus",
    image: "https://picsum.photos/seed/product88/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Crimson",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 89,
    name: "Raychel",
    price: 994.01,
    status: "Stock_Out",
    stock: 996,
    description:
      "nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget",
    image: "https://picsum.photos/seed/product89/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Blue",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 90,
    name: "Normand",
    price: 719.03,
    status: "Stock_Out",
    stock: 969,
    description:
      "praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante",
    image: "https://picsum.photos/seed/product90/300/300.webp",
    category: "home decor",
    subcategory: "laptops",
    color: "Orange",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 91,
    name: "Christy",
    price: 850.54,
    status: "Stock_Out",
    stock: 521,
    description:
      "sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet",
    image: "https://picsum.photos/seed/product91/300/300.webp",
    category: "clothing",
    subcategory: "dresses",
    color: "Blue",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 92,
    name: "Frankie",
    price: 137.4,
    status: "Stock_Out",
    stock: 8,
    description:
      "a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra",
    image: "https://picsum.photos/seed/product92/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Crimson",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 93,
    name: "Trstram",
    price: 458.32,
    status: "active",
    stock: 18,
    description:
      "lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed",
    image: "https://picsum.photos/seed/product93/300/300.webp",
    category: "clothing",
    subcategory: "pillows",
    color: "Khaki",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 94,
    name: "Sallyanne",
    price: 173.19,
    status: "active",
    stock: 998,
    description:
      "sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at",
    image: "https://picsum.photos/seed/product94/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Purple",
    size: "small",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 95,
    name: "Harriet",
    price: 546.8,
    status: "active",
    stock: 283,
    description:
      "pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum",
    image: "https://picsum.photos/seed/product95/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Aquamarine",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 96,
    name: "Ellsworth",
    price: 882.81,
    status: "Stock_Out",
    stock: 417,
    description:
      "et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id",
    image: "https://picsum.photos/seed/product96/300/300.webp",
    category: "electronics",
    subcategory: "pillows",
    color: "Yellow",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 97,
    name: "Eldridge",
    price: 982.21,
    status: "Draft",
    stock: 733,
    description:
      "nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed",
    image: "https://picsum.photos/seed/product97/300/300.webp",
    category: "home decor",
    subcategory: "pillows",
    color: "Red",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 98,
    name: "Jeanelle",
    price: 257.98,
    status: "Stock_Out",
    stock: 851,
    description:
      "turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis",
    image: "https://picsum.photos/seed/product98/300/300.webp",
    category: "electronics",
    subcategory: "dresses",
    color: "Yellow",
    size: "medium",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 99,
    name: "Morgana",
    price: 973.37,
    status: "Draft",
    stock: 552,
    description:
      "habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam",
    image: "https://picsum.photos/seed/product99/300/300.webp",
    category: "home decor",
    subcategory: "dresses",
    color: "Mauv",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
  {
    id: 100,
    name: "Sloane",
    price: 238.15,
    status: "Stock_Out",
    stock: 256,
    description:
      "integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam",
    image: "https://picsum.photos/seed/product100/300/300.webp",
    category: "electronics",
    subcategory: "laptops",
    color: "Indigo",
    size: "large",
    Created_At: "2024-06-27T10:21:51.279+00:00",
  },
];

export { columns, users, statusOptions };
